package org.onekash.kashcal.widget

import android.content.Context
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.glance.color.ColorProviders
import androidx.glance.color.colorProviders
import androidx.glance.material3.ColorProviders
import kotlinx.coroutines.flow.first
import org.onekash.kashcal.data.preferences.KashCalDataStore
import org.onekash.kashcal.ui.theme.ColorSource
import org.onekash.kashcal.ui.theme.ThemeMode
import org.onekash.kashcal.ui.theme.WIDGET_ACCENT_CONTRAST_LEVEL
import org.onekash.kashcal.ui.theme.accentColorScheme

/**
 * Builds Glance [ColorProviders] from an accent seed, so widgets recolor with the same accent
 * the app uses. Light and dark are generated by the shared [accentColorScheme] (pure HCT, no
 * Context/composition), then handed to Glance's Material 3 interop, which picks light vs dark
 * against the system day/night setting at render time — unless [forceDark] pins one face, in
 * which case the forced scheme is published as BOTH the day and the night palette so Glance's
 * day/night pick can no longer reach the other face.
 *
 * Widgets build the scheme at [WIDGET_ACCENT_CONTRAST_LEVEL] (a small positive axis): the header
 * rides the muted `secondaryContainer` role. Its text (`onSecondaryContainer`) is a
 * guaranteed-contrast M3 pair with it, so it clears AA for any seed by construction — including the
 * wallpaper-derived automatic accent; the low axis lifts it to a comfortable ~5:1 across the tested
 * palette while holding the header at nearly the body's tone, so the two read as one near-uniform
 * tinted panel rather than a header band over a plainer body.
 *
 * Widgets also opt out of the achromatic-container snap (`snapAchromaticContainers = false`). The
 * header rides `secondaryContainer`; snapping that role to pure white/black for the white/black
 * seeds would blow the header out to the extreme instead of the muted accent tone. At this low
 * contrast level the raw engine already gives the achromatic header 5:1+ text, so the snap is
 * unnecessary here.
 *
 * Finally, the body (`widgetBackground`) is pinned to `surfaceVariant` — the most-tinted body role
 * that keeps item text at full contrast for every seed. `secondaryContainer` carries more chroma,
 * but its non-guaranteed pairing with `onSurface`/`onSurfaceVariant` drops below WCAG AA for
 * saturated seeds (measured item text as low as ~2.5:1), so it is not a safe body. `surfaceVariant`
 * still shows a visible accent tint (chroma up to ~0.15 for chromatic seeds) while keeping item text
 * at ~7:1+ (onSurface) and secondary text at ~5.5:1+ (onSurfaceVariant).
 *
 * This is only reached for the SEED accent. The automatic (Material You) source does NOT come
 * through here — it renders on the device's genuine dynamic palette (see [resolveWidgetAccentColors]).
 */
fun accentColorProviders(seed: Int, forceDark: Boolean? = null): ColorProviders {
    val light = accentColorScheme(
        seed, dark = false,
        contrastLevel = WIDGET_ACCENT_CONTRAST_LEVEL,
        snapAchromaticContainers = false,
    )
    val dark = accentColorScheme(
        seed, dark = true,
        contrastLevel = WIDGET_ACCENT_CONTRAST_LEVEL,
        snapAchromaticContainers = false,
    )
    // A pinned face publishes its scheme as both day and night; otherwise light rides day and
    // dark rides night, and Glance picks against the system setting at render time.
    val (day, night) = when (forceDark) {
        null -> light to dark
        true -> dark to dark
        false -> light to light
    }
    // Base carries every role wired from the two schemes via Glance's Material 3 interop; we then
    // republish it through the core DSL overriding ONLY widgetBackground -> surfaceVariant. Reading roles
    // back off `base` keeps all other roles in lockstep with the interop (no 26-way manual mirror).
    val base = ColorProviders(light = day, dark = night)
    // A pure-black or pure-white seed has no hue for the HCT engine to preserve, so the raw scheme
    // collapses onto a muddy neutral gray ("I picked black, the widget is gray"). For those two seeds
    // only, snap to a crisp monochrome panel — every painted background role to the pure extreme,
    // every text/on-role to the readable inverse, with the dimmed tiers stepped to gray so the
    // hierarchy survives. Every other seed falls through untouched.
    monochromeSnap(seed, base)?.let { return it }
    return colorProviders(
        primary = base.primary,
        onPrimary = base.onPrimary,
        primaryContainer = base.primaryContainer,
        onPrimaryContainer = base.onPrimaryContainer,
        secondary = base.secondary,
        onSecondary = base.onSecondary,
        secondaryContainer = base.secondaryContainer,
        onSecondaryContainer = base.onSecondaryContainer,
        tertiary = base.tertiary,
        onTertiary = base.onTertiary,
        tertiaryContainer = base.tertiaryContainer,
        onTertiaryContainer = base.onTertiaryContainer,
        error = base.error,
        errorContainer = base.errorContainer,
        onError = base.onError,
        onErrorContainer = base.onErrorContainer,
        background = base.background,
        onBackground = base.onBackground,
        surface = base.surface,
        onSurface = base.onSurface,
        surfaceVariant = base.surfaceVariant,
        onSurfaceVariant = base.onSurfaceVariant,
        outline = base.outline,
        inverseOnSurface = base.inverseOnSurface,
        inverseSurface = base.inverseSurface,
        inversePrimary = base.inversePrimary,
        widgetBackground = base.surfaceVariant,
    )
}

/** Packed ARGB for the two achromatic-extreme seeds the picker offers. */
private const val PURE_WHITE_SEED: Int = 0xFFFFFFFF.toInt()
private const val PURE_BLACK_SEED: Int = 0xFF000000.toInt()

/** A neutral gray at [t] of the way from [ink] toward [panel] (t in 0..1); stays perfectly gray. */
private fun grayBetween(ink: Color, panel: Color, t: Float): Color =
    Color(
        red = ink.red + (panel.red - ink.red) * t,
        green = ink.green + (panel.green - ink.green) * t,
        blue = ink.blue + (panel.blue - ink.blue) * t,
    )

/**
 * For a pure-black / pure-white accent seed, republishes [base] as a crisp monochrome panel;
 * returns null for every other seed (fall through to the tinted path).
 *
 * `panel` is the pure extreme every painted background role snaps to (secondaryContainer header +
 * footer, surfaceVariant/widgetBackground body). `ink` is the pure inverse the text roles take. The
 * two dimmed tiers step from `ink` toward `panel` so the hierarchy the widget relies on survives a
 * flat 21:1 wall: secondary copy (onSurfaceVariant — event times, subtitles) at 30% and the
 * de-emphasis tier (outline — past events, the transient sync glyph) at 50%. Both stay neutral gray
 * and the 30% step keeps secondary comfortably above WCAG AA against the panel.
 *
 * `primary` is deliberately the INK, not the panel: it is both the today-marker fill AND accent text
 * drawn on the body (e.g. "+N more", the empty-state "add event"), so it must be the readable ink —
 * a white today-circle with a black number on the black panel. `onPrimary` is therefore the panel.
 * Applies identically to both faces because `base`'s day/night were already pinned upstream when a
 * face is forced; when unpinned, both faces resolve to the same monochrome by construction.
 */
private fun monochromeSnap(seed: Int, base: ColorProviders): ColorProviders? {
    val (panel, ink) = when (seed) {
        PURE_BLACK_SEED -> Color.Black to Color.White
        PURE_WHITE_SEED -> Color.White to Color.Black
        else -> return null
    }
    val secondary = grayBetween(ink, panel, 0.30f) // event times, subtitles — dimmed but >= AA
    val dim = grayBetween(ink, panel, 0.50f)        // past events, transient sync glyph
    // Every role resolves to one flat color for BOTH faces — the snap pins the panel regardless of
    // the system day/night pick, so a black seed is a black widget in light mode too.
    return colorProviders(
        primary = flat(ink),
        onPrimary = flat(panel),
        primaryContainer = flat(panel),
        onPrimaryContainer = flat(ink),
        secondary = flat(ink),
        onSecondary = flat(panel),
        secondaryContainer = flat(panel),
        onSecondaryContainer = flat(ink),
        tertiary = flat(ink),
        onTertiary = flat(panel),
        tertiaryContainer = flat(panel),
        onTertiaryContainer = flat(ink),
        // Error stays the real accent-scheme error red — a monochrome panel shouldn't mute a
        // genuine error tone. (No widget currently paints it, but keep it correct.)
        error = base.error,
        errorContainer = base.errorContainer,
        onError = base.onError,
        onErrorContainer = base.onErrorContainer,
        background = flat(panel),
        onBackground = flat(ink),
        surface = flat(panel),
        onSurface = flat(ink),
        surfaceVariant = flat(panel),
        onSurfaceVariant = flat(secondary),
        outline = flat(dim),
        inverseOnSurface = flat(panel),
        inverseSurface = flat(ink),
        inversePrimary = flat(panel),
        widgetBackground = flat(panel),
    )
}

/** A Glance day/night provider that resolves to [color] for both faces (the monochrome snap is flat). */
private fun flat(color: Color) = androidx.glance.color.ColorProvider(day = color, night = color)

/**
 * The colors a widget should render with.
 *
 * @param colors the resolved [ColorProviders], or null to use the platform's genuine Material You
 *   palette (`GlanceTheme.colors` at the call site — the `accentColors ?: GlanceTheme.colors`
 *   fallback). Only null for the DYNAMIC source following the system day/night setting; a pinned
 *   face always yields concrete providers because the platform palette must then be re-published
 *   with both faces set to the forced one.
 * @param forcedDark the widget's light/dark pin: null = follow the system, true = forced dark,
 *   false = forced light. Call sites that render static day/night colors outside the Glance scheme
 *   (e.g. the month grid's adjacent-month text) use this to match the pinned face.
 */
data class WidgetColorConfig(
    val colors: ColorProviders?,
    val forcedDark: Boolean?,
)

/**
 * Resolves the colors a widget should use, honoring the widget-specific appearance settings
 * ([WidgetColorSource] + [WidgetThemeSource]) which are independent of, but able to track, the app face.
 *
 * Color source:
 * - **FOLLOW_APP** (default): mirror the app's color-source resolution (including the
 *   retired-teal migration) so app and widgets stay in sync, exactly as before the widget
 *   settings existed.
 * - **SEED** (widget accent picker): builds tinted providers via [accentColorProviders] from the
 *   widget-only seed — the same scheme generator the app face uses.
 * - **DYNAMIC**: renders on the device's genuine Material You palette.
 *
 * Light/dark face (applies to EVERY source):
 * - **Follow app**: adopt the app's own face. When the app follows the device, the widget resolves
 *   to null so it follows the device too — SEED providers carry both faces and Glance picks at
 *   render time; DYNAMIC's genuine palette shows through. We do NOT reseed a scheme from a single
 *   system-accent tone here: that overwrote the real dynamic palette (near-neutral system surfaces,
 *   accent where the system places it) with an app-derived tint, so the widget stopped matching the
 *   launcher and system UI.
 * - **Light/Dark**: the face is pinned by publishing the forced scheme as both the day and night
 *   palette. For DYNAMIC that means re-publishing the platform's own dynamic scheme for the forced
 *   face (via [dynamicScheme]) instead of deferring to the system's day/night pick.
 *
 * @param dynamicScheme builds the platform dynamic scheme for a face; injectable so unit tests
 *   don't need a Context-backed palette. Defaults to the real dynamic schemes (always available:
 *   minSdk 31).
 */
suspend fun resolveWidgetAccentColors(
    context: Context,
    dataStore: KashCalDataStore,
    dynamicScheme: (dark: Boolean) -> ColorScheme = { dark ->
        if (dark) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
    },
): WidgetColorConfig {
    // The app's theme feeds both the follow-app face below and the follow-app color source's
    // retired-teal migration, so read it once here.
    val appTheme = dataStore.theme.first()
    val forcedDark: Boolean? = when (WidgetThemeSource.fromPrefValue(dataStore.widgetThemeSource.first())) {
        WidgetThemeSource.LIGHT -> false
        WidgetThemeSource.DARK -> true
        // Follow app: adopt the app's own face. When the app itself follows the device, that face
        // is null and the widget resolves to null too — so this transitively covers device-following
        // without a separate "system" option.
        WidgetThemeSource.FOLLOW_APP -> ThemeMode.fromPrefValue(appTheme).forcedDark
    }
    return when (WidgetColorSource.fromPrefValue(dataStore.widgetColorSource.first())) {
        WidgetColorSource.SEED ->
            WidgetColorConfig(accentColorProviders(dataStore.widgetAccentSeed.first(), forcedDark), forcedDark)
        WidgetColorSource.DYNAMIC -> dynamicConfig(forcedDark, dynamicScheme)
        WidgetColorSource.FOLLOW_APP -> {
            // Mirror the app's color-source resolution (including the retired-teal migration).
            val appSource = ColorSource.fromPrefValue(
                explicit = dataStore.colorSource.first(),
                legacyTheme = appTheme,
            )
            when (appSource) {
                ColorSource.SEED ->
                    WidgetColorConfig(accentColorProviders(dataStore.accentSeed.first(), forcedDark), forcedDark)
                ColorSource.DYNAMIC -> dynamicConfig(forcedDark, dynamicScheme)
            }
        }
    }
}

/**
 * DYNAMIC-source config: null colors on the system face (genuine platform palette at the call
 * site), or the platform's own dynamic scheme pinned to the forced face.
 */
private fun dynamicConfig(
    forcedDark: Boolean?,
    dynamicScheme: (dark: Boolean) -> ColorScheme,
): WidgetColorConfig = when (forcedDark) {
    null -> WidgetColorConfig(colors = null, forcedDark = null)
    else -> {
        val pinned = dynamicScheme(forcedDark)
        WidgetColorConfig(ColorProviders(light = pinned, dark = pinned), forcedDark)
    }
}
